export const POST_ADMIN_YOGA_FORM_REQUEST = 'POST_ADMIN_YOGA_FORM_REQUEST';
export const POST_ADMIN_YOGA_FORM_SUCCESS = 'POST_ADMIN_YOGA_FORM_SUCCESS';
export const POST_ADMIN_YOGA_FORM_FAILURE = 'POST_ADMIN_YOGA_FORM_FAILURE';

export const GET_ADMIN_YOGA_FORM_REQUEST = 'GET_ADMIN_YOGA_FORM_REQUEST';
export const GET_ADMIN_YOGA_FORM_SUCCESS = 'GET_ADMIN_YOGA_FORM_SUCCESS';
export const GET_ADMIN_YOGA_FORM_FAILURE = 'GET_ADMIN_YOGA_FORM_FAILURE';

export const GET_SINGLE_ADMIN_YOGA_FORM_REQUEST = 'GET_SINGLE_ADMIN_YOGA_FORM_REQUEST';
export const GET_SINGLE_ADMIN_YOGA_FORM_SUCCESS = 'GET_SINGLE_ADMIN_YOGA_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_YOGA_FORM_FAILURE = 'GET_SINGLE_ADMIN_YOGA_FORM_FAILURE';

export const DELETE_ADMIN_YOGA_FORM_REQUEST = 'DELETE_ADMIN_YOGA_FORM_REQUEST';
export const DELETE_ADMIN_YOGA_FORM_SUCCESS = 'DELETE_ADMIN_YOGA_FORM_SUCCESS';
export const DELETE_ADMIN_YOGA_FORM_FAILURE = 'DELETE_ADMIN_YOGA_FORM_FAILURE';

export const UPDATE_ADMIN_YOGA_FORM_REQUEST = 'UPDATE_ADMIN_YOGA_FORM_REQUEST';
export const UPDATE_ADMIN_YOGA_FORM_SUCCESS = 'UPDATE_ADMIN_YOGA_FORM_SUCCESS';
export const UPDATE_ADMIN_YOGA_FORM_FAILURE = 'UPDATE_ADMIN_YOGA_FORM_FAILURE';

export const POST_ATTENDANCE_REQUEST = 'POST_ATTENDANCE_REQUEST';
export const POST_ATTENDANCE_SUCCESS = 'POST_ATTENDANCE_SUCCESS';
export const POST_ATTENDANCE_FAILURE = 'POST_ATTENDANCE_FAILURE';

export const GET_DATA_BASED_ON_LOCATION_AND_USERS_REQUEST = 'GET_DATA_BASED_ON_LOCATION_AND_USERS_REQUEST';
export const GET_DATA_BASED_ON_LOCATION_AND_USERS_SUCCESS = 'GET_DATA_BASED_ON_LOCATION_AND_USERS_SUCCESS';
export const GET_DATA_BASED_ON_LOCATION_AND_USERS_FAILURE = 'GET_DATA_BASED_ON_LOCATION_AND_USERS_FAILURE';







export const POST_ADMIN_SECRET_FORM_REQUEST = 'POST_ADMIN_SECRET_FORM_REQUEST';
export const POST_ADMIN_SECRET_FORM_SUCCESS = 'POST_ADMIN_SECRET_FORM_SUCCESS';
export const POST_ADMIN_SECRET_FORM_FAILURE = 'POST_ADMIN_SECRET_FORM_FAILURE';

export const GET_ADMIN_SECRET_FORM_REQUEST = 'GET_ADMIN_SECRET_FORM_REQUEST';
export const GET_ADMIN_SECRET_FORM_SUCCESS = 'GET_ADMIN_SECRET_FORM_SUCCESS';
export const GET_ADMIN_SECRET_FORM_FAILURE = 'GET_ADMIN_SECRET_FORM_FAILURE';

export const GET_SINGLE_ADMIN_SECRET_FORM_REQUEST = 'GET_SINGLE_ADMIN_SECRET_FORM_REQUEST';
export const GET_SINGLE_ADMIN_SECRET_FORM_SUCCESS = 'GET_SINGLE_ADMIN_SECRET_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_SECRET_FORM_FAILURE = 'GET_SINGLE_ADMIN_SECRET_FORM_FAILURE';

export const DELETE_ADMIN_SECRET_FORM_REQUEST = 'DELETE_ADMIN_SECRET_FORM_REQUEST';
export const DELETE_ADMIN_SECRET_FORM_SUCCESS = 'DELETE_ADMIN_SECRET_FORM_SUCCESS';
export const DELETE_ADMIN_SECRET_FORM_FAILURE = 'DELETE_ADMIN_SECRET_FORM_FAILURE';

export const UPDATE_ADMIN_SECRET_FORM_REQUEST = 'UPDATE_ADMIN_SECRET_FORM_REQUEST';
export const UPDATE_ADMIN_SECRET_FORM_SUCCESS = 'UPDATE_ADMIN_SECRET_FORM_SUCCESS';
export const UPDATE_ADMIN_SECRET_FORM_FAILURE = 'UPDATE_ADMIN_SECRET_FORM_FAILURE';

export const POST_SECRET_ATTENDANCE_REQUEST = 'POST_SECRET_ATTENDANCE_REQUEST';
export const POST_SECRET_ATTENDANCE_SUCCESS = 'POST_SECRET_ATTENDANCE_SUCCESS';
export const POST_SECRET_ATTENDANCE_FAILURE = 'POST_SECRET_ATTENDANCE_FAILURE';


export const GET_SECRET_DATA_BASED_ON_LOCATION_AND_USERS_REQUEST = 'GET_SECRET_DATA_BASED_ON_LOCATION_AND_USERS_REQUEST';
export const GET_SECRET_DATA_BASED_ON_LOCATION_AND_USERS_SUCCESS = 'GET_SECRET_DATA_BASED_ON_LOCATION_AND_USERS_SUCCESS';
export const GET_SECRET_DATA_BASED_ON_LOCATION_AND_USERS_FAILURE = 'GET_SECRET_DATA_BASED_ON_LOCATION_AND_USERS_FAILURE';







export const POST_ADMIN_MIND_CONTROL_FORM_REQUEST = 'POST_ADMIN_MIND_CONTROL_FORM_REQUEST';
export const POST_ADMIN_MIND_CONTROL_FORM_SUCCESS = 'POST_ADMIN_MIND_CONTROL_FORM_SUCCESS';
export const POST_ADMIN_MIND_CONTROL_FORM_FAILURE = 'POST_ADMIN_MIND_CONTROL_FORM_FAILURE';

export const GET_ADMIN_MIND_CONTROL_FORM_REQUEST = 'GET_ADMIN_MIND_CONTROL_FORM_REQUEST';
export const GET_ADMIN_MIND_CONTROL_FORM_SUCCESS = 'GET_ADMIN_MIND_CONTROL_FORM_SUCCESS';
export const GET_ADMIN_MIND_CONTROL_FORM_FAILURE = 'GET_ADMIN_MIND_CONTROL_FORM_FAILURE';

export const GET_SINGLE_ADMIN_MIND_CONTROL_FORM_REQUEST = 'GET_SINGLE_ADMIN_MIND_CONTROL_FORM_REQUEST';
export const GET_SINGLE_ADMIN_MIND_CONTROL_FORM_SUCCESS = 'GET_SINGLE_ADMIN_MIND_CONTROL_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_MIND_CONTROL_FORM_FAILURE = 'GET_SINGLE_ADMIN_MIND_CONTROL_FORM_FAILURE';

export const DELETE_ADMIN_MIND_CONTROL_FORM_REQUEST = 'DELETE_ADMIN_MIND_CONTROL_FORM_REQUEST';
export const DELETE_ADMIN_MIND_CONTROL_FORM_SUCCESS = 'DELETE_ADMIN_MIND_CONTROL_FORM_SUCCESS';
export const DELETE_ADMIN_MIND_CONTROL_FORM_FAILURE = 'DELETE_ADMIN_MIND_CONTROL_FORM_FAILURE';

export const UPDATE_ADMIN_MIND_CONTROL_FORM_REQUEST = 'UPDATE_ADMIN_MIND_CONTROL_FORM_REQUEST';
export const UPDATE_ADMIN_MIND_CONTROL_FORM_SUCCESS = 'UPDATE_ADMIN_MIND_CONTROL_FORM_SUCCESS';
export const UPDATE_ADMIN_MIND_CONTROL_FORM_FAILURE = 'UPDATE_ADMIN_MIND_CONTROL_FORM_FAILURE';

export const POST_MIND_CONTROL_ATTENDANCE_REQUEST = 'POST_MIND_CONTROL_ATTENDANCE_REQUEST';
export const POST_MIND_CONTROL_ATTENDANCE_SUCCESS = 'POST_MIND_CONTROL_ATTENDANCE_SUCCESS';
export const POST_MIND_CONTROL_ATTENDANCE_FAILURE = 'POST_MIND_CONTROL_ATTENDANCE_FAILURE';


export const GET_MIND_CONTROL_DATA_BASED_ON_LOCATION_AND_USERS_REQUEST = 'GET_MIND_CONTROL_DATA_BASED_ON_LOCATION_AND_USERS_REQUEST';
export const GET_MIND_CONTROL_DATA_BASED_ON_LOCATION_AND_USERS_SUCCESS = 'GET_MIND_CONTROL_DATA_BASED_ON_LOCATION_AND_USERS_SUCCESS';
export const GET_MIND_CONTROL_DATA_BASED_ON_LOCATION_AND_USERS_FAILURE = 'GET_MIND_CONTROL_DATA_BASED_ON_LOCATION_AND_USERS_FAILURE';






export const POST_ADMIN_TRIPS_FORM_REQUEST = 'POST_ADMIN_TRIPS_FORM_REQUEST';
export const POST_ADMIN_TRIPS_FORM_SUCCESS = 'POST_ADMIN_TRIPS_FORM_SUCCESS';
export const POST_ADMIN_TRIPS_FORM_FAILURE = 'POST_ADMIN_TRIPS_FORM_FAILURE';

export const GET_ADMIN_TRIPS_FORM_REQUEST = 'GET_ADMIN_TRIPS_FORM_REQUEST';
export const GET_ADMIN_TRIPS_FORM_SUCCESS = 'GET_ADMIN_TRIPS_FORM_SUCCESS';
export const GET_ADMIN_TRIPS_FORM_FAILURE = 'GET_ADMIN_TRIPS_FORM_FAILURE';

export const GET_SINGLE_ADMIN_TRIPS_FORM_REQUEST = 'GET_SINGLE_ADMIN_TRIPS_FORM_REQUEST';
export const GET_SINGLE_ADMIN_TRIPS_FORM_SUCCESS = 'GET_SINGLE_ADMIN_TRIPS_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_TRIPS_FORM_FAILURE = 'GET_SINGLE_ADMIN_TRIPS_FORM_FAILURE';

export const DELETE_ADMIN_TRIPS_FORM_REQUEST = 'DELETE_ADMIN_TRIPS_FORM_REQUEST';
export const DELETE_ADMIN_TRIPS_FORM_SUCCESS = 'DELETE_ADMIN_TRIPS_FORM_SUCCESS';
export const DELETE_ADMIN_TRIPS_FORM_FAILURE = 'DELETE_ADMIN_TRIPS_FORM_FAILURE';

export const UPDATE_ADMIN_TRIPS_FORM_REQUEST = 'UPDATE_ADMIN_TRIPS_FORM_REQUEST';
export const UPDATE_ADMIN_TRIPS_FORM_SUCCESS = 'UPDATE_ADMIN_TRIPS_FORM_SUCCESS';
export const UPDATE_ADMIN_TRIPS_FORM_FAILURE = 'UPDATE_ADMIN_TRIPS_FORM_FAILURE';

export const POST_TRIPS_ATTENDANCE_REQUEST = 'POST_TRIPS_ATTENDANCE_REQUEST';
export const POST_TRIPS_ATTENDANCE_SUCCESS = 'POST_TRIPS_ATTENDANCE_SUCCESS';
export const POST_TRIPS_ATTENDANCE_FAILURE = 'POST_TRIPS_ATTENDANCE_FAILURE';


export const GET_TRIPS_DATA_BASED_ON_LOCATION_AND_USERS_REQUEST = 'GET_TRIPS_DATA_BASED_ON_LOCATION_AND_USERS_REQUEST';
export const GET_TRIPS_DATA_BASED_ON_LOCATION_AND_USERS_SUCCESS = 'GET_TRIPS_DATA_BASED_ON_LOCATION_AND_USERS_SUCCESS';
export const GET_TRIPS_DATA_BASED_ON_LOCATION_AND_USERS_FAILURE = 'GET_TRIPS_DATA_BASED_ON_LOCATION_AND_USERS_FAILURE';







export const POST_ADMIN_RESIDENCY_FORM_REQUEST = 'POST_ADMIN_RESIDENCY_FORM_REQUEST';
export const POST_ADMIN_RESIDENCY_FORM_SUCCESS = 'POST_ADMIN_RESIDENCY_FORM_SUCCESS';
export const POST_ADMIN_RESIDENCY_FORM_FAILURE = 'POST_ADMIN_RESIDENCY_FORM_FAILURE';

export const GET_ADMIN_RESIDENCY_FORM_REQUEST = 'GET_ADMIN_RESIDENCY_FORM_REQUEST';
export const GET_ADMIN_RESIDENCY_FORM_SUCCESS = 'GET_ADMIN_RESIDENCY_FORM_SUCCESS';
export const GET_ADMIN_RESIDENCY_FORM_FAILURE = 'GET_ADMIN_RESIDENCY_FORM_FAILURE';

export const GET_SINGLE_ADMIN_RESIDENCY_FORM_REQUEST = 'GET_SINGLE_ADMIN_RESIDENCY_FORM_REQUEST';
export const GET_SINGLE_ADMIN_RESIDENCY_FORM_SUCCESS = 'GET_SINGLE_ADMIN_RESIDENCY_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_RESIDENCY_FORM_FAILURE = 'GET_SINGLE_ADMIN_RESIDENCY_FORM_FAILURE';

export const DELETE_ADMIN_RESIDENCY_FORM_REQUEST = 'DELETE_ADMIN_RESIDENCY_FORM_REQUEST';
export const DELETE_ADMIN_RESIDENCY_FORM_SUCCESS = 'DELETE_ADMIN_RESIDENCY_FORM_SUCCESS';
export const DELETE_ADMIN_RESIDENCY_FORM_FAILURE = 'DELETE_ADMIN_RESIDENCY_FORM_FAILURE';

export const UPDATE_ADMIN_RESIDENCY_FORM_REQUEST = 'UPDATE_ADMIN_RESIDENCY_FORM_REQUEST';
export const UPDATE_ADMIN_RESIDENCY_FORM_SUCCESS = 'UPDATE_ADMIN_RESIDENCY_FORM_SUCCESS';
export const UPDATE_ADMIN_RESIDENCY_FORM_FAILURE = 'UPDATE_ADMIN_RESIDENCY_FORM_FAILURE';







export const POST_ADMIN_FESTIVALS_FORM_REQUEST = 'POST_ADMIN_FESTIVALS_FORM_REQUEST';
export const POST_ADMIN_FESTIVALS_FORM_SUCCESS = 'POST_ADMIN_FESTIVALS_FORM_SUCCESS';
export const POST_ADMIN_FESTIVALS_FORM_FAILURE = 'POST_ADMIN_FESTIVALS_FORM_FAILURE';

export const GET_ADMIN_FESTIVALS_FORM_REQUEST = 'GET_ADMIN_FESTIVALS_FORM_REQUEST';
export const GET_ADMIN_FESTIVALS_FORM_SUCCESS = 'GET_ADMIN_FESTIVALS_FORM_SUCCESS';
export const GET_ADMIN_FESTIVALS_FORM_FAILURE = 'GET_ADMIN_FESTIVALS_FORM_FAILURE';

export const GET_SINGLE_ADMIN_FESTIVALS_FORM_REQUEST = 'GET_SINGLE_ADMIN_FESTIVALS_FORM_REQUEST';
export const GET_SINGLE_ADMIN_FESTIVALS_FORM_SUCCESS = 'GET_SINGLE_ADMIN_FESTIVALS_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_FESTIVALS_FORM_FAILURE = 'GET_SINGLE_ADMIN_FESTIVALS_FORM_FAILURE';

export const DELETE_ADMIN_FESTIVALS_FORM_REQUEST = 'DELETE_ADMIN_FESTIVALS_FORM_REQUEST';
export const DELETE_ADMIN_FESTIVALS_FORM_SUCCESS = 'DELETE_ADMIN_FESTIVALS_FORM_SUCCESS';
export const DELETE_ADMIN_FESTIVALS_FORM_FAILURE = 'DELETE_ADMIN_FESTIVALS_FORM_FAILURE';

export const UPDATE_ADMIN_FESTIVALS_FORM_REQUEST = 'UPDATE_ADMIN_FESTIVALS_FORM_REQUEST';
export const UPDATE_ADMIN_FESTIVALS_FORM_SUCCESS = 'UPDATE_ADMIN_FESTIVALS_FORM_SUCCESS';
export const UPDATE_ADMIN_FESTIVALS_FORM_FAILURE = 'UPDATE_ADMIN_FESTIVALS_FORM_FAILURE';

export const POST_FESTIVALS_ATTENDANCE_REQUEST = 'POST_FESTIVALS_ATTENDANCE_REQUEST';
export const POST_FESTIVALS_ATTENDANCE_SUCCESS = 'POST_FESTIVALS_ATTENDANCE_SUCCESS';
export const POST_FESTIVALS_ATTENDANCE_FAILURE = 'POST_FESTIVALS_ATTENDANCE_FAILURE';


export const GET_FESTIVALS_DATA_BASED_ON_LOCATION_AND_USERS_REQUEST = 'GET_FESTIVALS_DATA_BASED_ON_LOCATION_AND_USERS_REQUEST';
export const GET_FESTIVALS_DATA_BASED_ON_LOCATION_AND_USERS_SUCCESS = 'GET_FESTIVALS_DATA_BASED_ON_LOCATION_AND_USERS_SUCCESS';
export const GET_FESTIVALS_DATA_BASED_ON_LOCATION_AND_USERS_FAILURE = 'GET_FESTIVALS_DATA_BASED_ON_LOCATION_AND_USERS_FAILURE';





export const POST_ADMIN_BLOGS_FORM_REQUEST = 'POST_ADMIN_BLOGS_FORM_REQUEST';
export const POST_ADMIN_BLOGS_FORM_SUCCESS = 'POST_ADMIN_BLOGS_FORM_SUCCESS';
export const POST_ADMIN_BLOGS_FORM_FAILURE = 'POST_ADMIN_BLOGS_FORM_FAILURE';

export const GET_ADMIN_BLOGS_FORM_REQUEST = 'GET_ADMIN_BLOGS_FORM_REQUEST';
export const GET_ADMIN_BLOGS_FORM_SUCCESS = 'GET_ADMIN_BLOGS_FORM_SUCCESS';
export const GET_ADMIN_BLOGS_FORM_FAILURE = 'GET_ADMIN_BLOGS_FORM_FAILURE';

export const GET_SINGLE_ADMIN_BLOGS_FORM_REQUEST = 'GET_SINGLE_ADMIN_BLOGS_FORM_REQUEST';
export const GET_SINGLE_ADMIN_BLOGS_FORM_SUCCESS = 'GET_SINGLE_ADMIN_BLOGS_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_BLOGS_FORM_FAILURE = 'GET_SINGLE_ADMIN_BLOGS_FORM_FAILURE';

export const DELETE_ADMIN_BLOGS_FORM_REQUEST = 'DELETE_ADMIN_BLOGS_FORM_REQUEST';
export const DELETE_ADMIN_BLOGS_FORM_SUCCESS = 'DELETE_ADMIN_BLOGS_FORM_SUCCESS';
export const DELETE_ADMIN_BLOGS_FORM_FAILURE = 'DELETE_ADMIN_BLOGS_FORM_FAILURE';

export const UPDATE_ADMIN_BLOGS_FORM_REQUEST = 'UPDATE_ADMIN_BLOGS_FORM_REQUEST';
export const UPDATE_ADMIN_BLOGS_FORM_SUCCESS = 'UPDATE_ADMIN_BLOGS_FORM_SUCCESS';
export const UPDATE_ADMIN_BLOGS_FORM_FAILURE = 'UPDATE_ADMIN_BLOGS_FORM_FAILURE';






export const POST_ADMIN_GALLERY_FORM_REQUEST = 'POST_ADMIN_GALLERY_FORM_REQUEST';
export const POST_ADMIN_GALLERY_FORM_SUCCESS = 'POST_ADMIN_GALLERY_FORM_SUCCESS';
export const POST_ADMIN_GALLERY_FORM_FAILURE = 'POST_ADMIN_GALLERY_FORM_FAILURE';

export const GET_ADMIN_GALLERY_FORM_REQUEST = 'GET_ADMIN_GALLERY_FORM_REQUEST';
export const GET_ADMIN_GALLERY_FORM_SUCCESS = 'GET_ADMIN_GALLERY_FORM_SUCCESS';
export const GET_ADMIN_GALLERY_FORM_FAILURE = 'GET_ADMIN_GALLERY_FORM_FAILURE';

export const GET_SINGLE_ADMIN_GALLERY_FORM_REQUEST = 'GET_SINGLE_ADMIN_GALLERY_FORM_REQUEST';
export const GET_SINGLE_ADMIN_GALLERY_FORM_SUCCESS = 'GET_SINGLE_ADMIN_GALLERY_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_GALLERY_FORM_FAILURE = 'GET_SINGLE_ADMIN_GALLERY_FORM_FAILURE';

export const DELETE_ADMIN_GALLERY_FORM_REQUEST = 'DELETE_ADMIN_GALLERY_FORM_REQUEST';
export const DELETE_ADMIN_GALLERY_FORM_SUCCESS = 'DELETE_ADMIN_GALLERY_FORM_SUCCESS';
export const DELETE_ADMIN_GALLERY_FORM_FAILURE = 'DELETE_ADMIN_GALLERY_FORM_FAILURE';

export const UPDATE_ADMIN_GALLERY_FORM_REQUEST = 'UPDATE_ADMIN_GALLERY_FORM_REQUEST';
export const UPDATE_ADMIN_GALLERY_FORM_SUCCESS = 'UPDATE_ADMIN_GALLERY_FORM_SUCCESS';
export const UPDATE_ADMIN_GALLERY_FORM_FAILURE = 'UPDATE_ADMIN_GALLERY_FORM_FAILURE';





export const POST_YOGA_FORM_REQUEST = 'POST_YOGA_FORM_REQUEST';
export const POST_YOGA_FORM_SUCCESS = 'POST_YOGA_FORM_SUCCESS';
export const POST_YOGA_FORM_FAILURE = 'POST_YOGA_FORM_FAILURE';

export const GET_YOGA_FORM_REQUEST = 'GET_YOGA_FORM_REQUEST';
export const GET_YOGA_FORM_SUCCESS = 'GET_YOGA_FORM_SUCCESS';
export const GET_YOGA_FORM_FAILURE = 'GET_YOGA_FORM_FAILURE';



export const POST_SECRET_OF_SUCCESS_FORM_REQUEST = 'POST_SECRET_OF_SUCCESS_FORM_REQUEST';
export const POST_SECRET_OF_SUCCESS_FORM_SUCCESS = 'POST_SECRET_OF_SUCCESS_FORM_SUCCESS';
export const POST_SECRET_OF_SUCCESS_FORM_FAILURE = 'POST_SECRET_OF_SUCCESS_FORM_FAILURE';

export const GET_SECRET_OF_SUCCESS_FORM_REQUEST = 'GET_SECRET_OF_SUCCESS_FORM_REQUEST';
export const GET_SECRET_OF_SUCCESS_FORM_SUCCESS = 'GET_SECRET_OF_SUCCESS_FORM_SUCCESS';
export const GET_SECRET_OF_SUCCESS_FORM_FAILURE = 'GET_SECRET_OF_SUCCESS_FORM_FAILURE';




export const POST__ART_OF_MIND_FORM_REQUEST = 'POST__ART_OF_MIND_FORM_REQUEST';
export const POST__ART_OF_MIND_FORM_SUCCESS = 'POST__ART_OF_MIND_FORM_SUCCESS';
export const POST__ART_OF_MIND_FORM_FAILURE = 'POST__ART_OF_MIND_FORM_FAILURE';

export const GET_ART_OF_MIND_FORM_REQUEST = 'GET_ART_OF_MIND_FORM_REQUEST';
export const GET_ART_OF_MIND_FORM_SUCCESS = 'GET_ART_OF_MIND_FORM_SUCCESS';
export const GET_ART_OF_MIND_FORM_FAILURE = 'GET_ART_OF_MIND_FORM_FAILURE';





export const POST_FESTIVALS_REQUEST = 'POST_FESTIVALS_REQUEST';
export const POST_FESTIVALS_SUCCESS = 'POST_FESTIVALS_SUCCESS';
export const POST_FESTIVALS_FAILURE = 'POST_FESTIVALS_FAILURE';

export const GET_FESTIVALS_REQUEST = 'GET_FESTIVALS_REQUEST';
export const GET_FESTIVALS_SUCCESS = 'GET_FESTIVALS_SUCCESS';
export const GET_FESTIVALS_FAILURE = 'GET_FESTIVALS_FAILURE';





export const POST_TRIPS_REQUEST = 'POST_TRIPS_REQUEST';
export const POST_TRIPS_SUCCESS = 'POST_TRIPS_SUCCESS';
export const POST_TRIPS_FAILURE = 'POST_TRIPS_FAILURE';

export const GET_TRIPS_REQUEST = 'GET_TRIPS_REQUEST';
export const GET_TRIPS_SUCCESS = 'GET_TRIPS_SUCCESS';
export const GET_TRIPS_FAILURE = 'GET_TRIPS_FAILURE';







