export const POST_ADMIN_YOGA_FORM_REQUEST = 'POST_ADMIN_YOGA_FORM_REQUEST';
export const POST_ADMIN_YOGA_FORM_SUCCESS = 'POST_ADMIN_YOGA_FORM_SUCCESS';
export const POST_ADMIN_YOGA_FORM_FAILURE = 'POST_ADMIN_YOGA_FORM_FAILURE';

export const GET_ADMIN_YOGA_FORM_REQUEST = 'GET_ADMIN_YOGA_FORM_REQUEST';
export const GET_ADMIN_YOGA_FORM_SUCCESS = 'GET_ADMIN_YOGA_FORM_SUCCESS';
export const GET_ADMIN_YOGA_FORM_FAILURE = 'GET_ADMIN_YOGA_FORM_FAILURE';

export const GET_SINGLE_ADMIN_YOGA_FORM_REQUEST = 'GET_SINGLE_ADMIN_YOGA_FORM_REQUEST';
export const GET_SINGLE_ADMIN_YOGA_FORM_SUCCESS = 'GET_SINGLE_ADMIN_YOGA_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_YOGA_FORM_FAILURE = 'GET_SINGLE_ADMIN_YOGA_FORM_FAILURE';

export const DELETE_ADMIN_YOGA_FORM_REQUEST = 'DELETE_ADMIN_YOGA_FORM_REQUEST';
export const DELETE_ADMIN_YOGA_FORM_SUCCESS = 'DELETE_ADMIN_YOGA_FORM_SUCCESS';
export const DELETE_ADMIN_YOGA_FORM_FAILURE = 'DELETE_ADMIN_YOGA_FORM_FAILURE';

export const UPDATE_ADMIN_YOGA_FORM_REQUEST = 'UPDATE_ADMIN_YOGA_FORM_REQUEST';
export const UPDATE_ADMIN_YOGA_FORM_SUCCESS = 'UPDATE_ADMIN_YOGA_FORM_SUCCESS';
export const UPDATE_ADMIN_YOGA_FORM_FAILURE = 'UPDATE_ADMIN_YOGA_FORM_FAILURE';




export const POST_ADMIN_SECRET_FORM_REQUEST = 'POST_ADMIN_SECRET_FORM_REQUEST';
export const POST_ADMIN_SECRET_FORM_SUCCESS = 'POST_ADMIN_SECRET_FORM_SUCCESS';
export const POST_ADMIN_SECRET_FORM_FAILURE = 'POST_ADMIN_SECRET_FORM_FAILURE';

export const GET_ADMIN_SECRET_FORM_REQUEST = 'GET_ADMIN_SECRET_FORM_REQUEST';
export const GET_ADMIN_SECRET_FORM_SUCCESS = 'GET_ADMIN_SECRET_FORM_SUCCESS';
export const GET_ADMIN_SECRET_FORM_FAILURE = 'GET_ADMIN_SECRET_FORM_FAILURE';

export const GET_SINGLE_ADMIN_SECRET_FORM_REQUEST = 'GET_SINGLE_ADMIN_SECRET_FORM_REQUEST';
export const GET_SINGLE_ADMIN_SECRET_FORM_SUCCESS = 'GET_SINGLE_ADMIN_SECRET_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_SECRET_FORM_FAILURE = 'GET_SINGLE_ADMIN_SECRET_FORM_FAILURE';

export const DELETE_ADMIN_SECRET_FORM_REQUEST = 'DELETE_ADMIN_SECRET_FORM_REQUEST';
export const DELETE_ADMIN_SECRET_FORM_SUCCESS = 'DELETE_ADMIN_SECRET_FORM_SUCCESS';
export const DELETE_ADMIN_SECRET_FORM_FAILURE = 'DELETE_ADMIN_SECRET_FORM_FAILURE';

export const UPDATE_ADMIN_SECRET_FORM_REQUEST = 'UPDATE_ADMIN_SECRET_FORM_REQUEST';
export const UPDATE_ADMIN_SECRET_FORM_SUCCESS = 'UPDATE_ADMIN_SECRET_FORM_SUCCESS';
export const UPDATE_ADMIN_SECRET_FORM_FAILURE = 'UPDATE_ADMIN_SECRET_FORM_FAILURE';




export const POST_ADMIN_MIND_CONTROL_FORM_REQUEST = 'POST_ADMIN_MIND_CONTROL_FORM_REQUEST';
export const POST_ADMIN_MIND_CONTROL_FORM_SUCCESS = 'POST_ADMIN_MIND_CONTROL_FORM_SUCCESS';
export const POST_ADMIN_MIND_CONTROL_FORM_FAILURE = 'POST_ADMIN_MIND_CONTROL_FORM_FAILURE';

export const GET_ADMIN_MIND_CONTROL_FORM_REQUEST = 'GET_ADMIN_MIND_CONTROL_FORM_REQUEST';
export const GET_ADMIN_MIND_CONTROL_FORM_SUCCESS = 'GET_ADMIN_MIND_CONTROL_FORM_SUCCESS';
export const GET_ADMIN_MIND_CONTROL_FORM_FAILURE = 'GET_ADMIN_MIND_CONTROL_FORM_FAILURE';

export const GET_SINGLE_ADMIN_MIND_CONTROL_FORM_REQUEST = 'GET_SINGLE_ADMIN_MIND_CONTROL_FORM_REQUEST';
export const GET_SINGLE_ADMIN_MIND_CONTROL_FORM_SUCCESS = 'GET_SINGLE_ADMIN_MIND_CONTROL_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_MIND_CONTROL_FORM_FAILURE = 'GET_SINGLE_ADMIN_MIND_CONTROL_FORM_FAILURE';

export const DELETE_ADMIN_MIND_CONTROL_FORM_REQUEST = 'DELETE_ADMIN_MIND_CONTROL_FORM_REQUEST';
export const DELETE_ADMIN_MIND_CONTROL_FORM_SUCCESS = 'DELETE_ADMIN_MIND_CONTROL_FORM_SUCCESS';
export const DELETE_ADMIN_MIND_CONTROL_FORM_FAILURE = 'DELETE_ADMIN_MIND_CONTROL_FORM_FAILURE';

export const UPDATE_ADMIN_MIND_CONTROL_FORM_REQUEST = 'UPDATE_ADMIN_MIND_CONTROL_FORM_REQUEST';
export const UPDATE_ADMIN_MIND_CONTROL_FORM_SUCCESS = 'UPDATE_ADMIN_MIND_CONTROL_FORM_SUCCESS';
export const UPDATE_ADMIN_MIND_CONTROL_FORM_FAILURE = 'UPDATE_ADMIN_MIND_CONTROL_FORM_FAILURE';






export const POST_ADMIN_TRIPS_FORM_REQUEST = 'POST_ADMIN_TRIPS_FORM_REQUEST';
export const POST_ADMIN_TRIPS_FORM_SUCCESS = 'POST_ADMIN_TRIPS_FORM_SUCCESS';
export const POST_ADMIN_TRIPS_FORM_FAILURE = 'POST_ADMIN_TRIPS_FORM_FAILURE';

export const GET_ADMIN_TRIPS_FORM_REQUEST = 'GET_ADMIN_TRIPS_FORM_REQUEST';
export const GET_ADMIN_TRIPS_FORM_SUCCESS = 'GET_ADMIN_TRIPS_FORM_SUCCESS';
export const GET_ADMIN_TRIPS_FORM_FAILURE = 'GET_ADMIN_TRIPS_FORM_FAILURE';

export const GET_SINGLE_ADMIN_TRIPS_FORM_REQUEST = 'GET_SINGLE_ADMIN_TRIPS_FORM_REQUEST';
export const GET_SINGLE_ADMIN_TRIPS_FORM_SUCCESS = 'GET_SINGLE_ADMIN_TRIPS_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_TRIPS_FORM_FAILURE = 'GET_SINGLE_ADMIN_TRIPS_FORM_FAILURE';

export const DELETE_ADMIN_TRIPS_FORM_REQUEST = 'DELETE_ADMIN_TRIPS_FORM_REQUEST';
export const DELETE_ADMIN_TRIPS_FORM_SUCCESS = 'DELETE_ADMIN_TRIPS_FORM_SUCCESS';
export const DELETE_ADMIN_TRIPS_FORM_FAILURE = 'DELETE_ADMIN_TRIPS_FORM_FAILURE';

export const UPDATE_ADMIN_TRIPS_FORM_REQUEST = 'UPDATE_ADMIN_TRIPS_FORM_REQUEST';
export const UPDATE_ADMIN_TRIPS_FORM_SUCCESS = 'UPDATE_ADMIN_TRIPS_FORM_SUCCESS';
export const UPDATE_ADMIN_TRIPS_FORM_FAILURE = 'UPDATE_ADMIN_TRIPS_FORM_FAILURE';




export const POST_ADMIN_RESIDENCY_FORM_REQUEST = 'POST_ADMIN_RESIDENCY_FORM_REQUEST';
export const POST_ADMIN_RESIDENCY_FORM_SUCCESS = 'POST_ADMIN_RESIDENCY_FORM_SUCCESS';
export const POST_ADMIN_RESIDENCY_FORM_FAILURE = 'POST_ADMIN_RESIDENCY_FORM_FAILURE';

export const GET_ADMIN_RESIDENCY_FORM_REQUEST = 'GET_ADMIN_RESIDENCY_FORM_REQUEST';
export const GET_ADMIN_RESIDENCY_FORM_SUCCESS = 'GET_ADMIN_RESIDENCY_FORM_SUCCESS';
export const GET_ADMIN_RESIDENCY_FORM_FAILURE = 'GET_ADMIN_RESIDENCY_FORM_FAILURE';

export const GET_SINGLE_ADMIN_RESIDENCY_FORM_REQUEST = 'GET_SINGLE_ADMIN_RESIDENCY_FORM_REQUEST';
export const GET_SINGLE_ADMIN_RESIDENCY_FORM_SUCCESS = 'GET_SINGLE_ADMIN_RESIDENCY_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_RESIDENCY_FORM_FAILURE = 'GET_SINGLE_ADMIN_RESIDENCY_FORM_FAILURE';

export const DELETE_ADMIN_RESIDENCY_FORM_REQUEST = 'DELETE_ADMIN_RESIDENCY_FORM_REQUEST';
export const DELETE_ADMIN_RESIDENCY_FORM_SUCCESS = 'DELETE_ADMIN_RESIDENCY_FORM_SUCCESS';
export const DELETE_ADMIN_RESIDENCY_FORM_FAILURE = 'DELETE_ADMIN_RESIDENCY_FORM_FAILURE';

export const UPDATE_ADMIN_RESIDENCY_FORM_REQUEST = 'UPDATE_ADMIN_RESIDENCY_FORM_REQUEST';
export const UPDATE_ADMIN_RESIDENCY_FORM_SUCCESS = 'UPDATE_ADMIN_RESIDENCY_FORM_SUCCESS';
export const UPDATE_ADMIN_RESIDENCY_FORM_FAILURE = 'UPDATE_ADMIN_RESIDENCY_FORM_FAILURE';







export const POST_ADMIN_FESTIVALS_FORM_REQUEST = 'POST_ADMIN_FESTIVALS_FORM_REQUEST';
export const POST_ADMIN_FESTIVALS_FORM_SUCCESS = 'POST_ADMIN_FESTIVALS_FORM_SUCCESS';
export const POST_ADMIN_FESTIVALS_FORM_FAILURE = 'POST_ADMIN_FESTIVALS_FORM_FAILURE';

export const GET_ADMIN_FESTIVALS_FORM_REQUEST = 'GET_ADMIN_FESTIVALS_FORM_REQUEST';
export const GET_ADMIN_FESTIVALS_FORM_SUCCESS = 'GET_ADMIN_FESTIVALS_FORM_SUCCESS';
export const GET_ADMIN_FESTIVALS_FORM_FAILURE = 'GET_ADMIN_FESTIVALS_FORM_FAILURE';

export const GET_SINGLE_ADMIN_FESTIVALS_FORM_REQUEST = 'GET_SINGLE_ADMIN_FESTIVALS_FORM_REQUEST';
export const GET_SINGLE_ADMIN_FESTIVALS_FORM_SUCCESS = 'GET_SINGLE_ADMIN_FESTIVALS_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_FESTIVALS_FORM_FAILURE = 'GET_SINGLE_ADMIN_FESTIVALS_FORM_FAILURE';

export const DELETE_ADMIN_FESTIVALS_FORM_REQUEST = 'DELETE_ADMIN_FESTIVALS_FORM_REQUEST';
export const DELETE_ADMIN_FESTIVALS_FORM_SUCCESS = 'DELETE_ADMIN_FESTIVALS_FORM_SUCCESS';
export const DELETE_ADMIN_FESTIVALS_FORM_FAILURE = 'DELETE_ADMIN_FESTIVALS_FORM_FAILURE';

export const UPDATE_ADMIN_FESTIVALS_FORM_REQUEST = 'UPDATE_ADMIN_FESTIVALS_FORM_REQUEST';
export const UPDATE_ADMIN_FESTIVALS_FORM_SUCCESS = 'UPDATE_ADMIN_FESTIVALS_FORM_SUCCESS';
export const UPDATE_ADMIN_FESTIVALS_FORM_FAILURE = 'UPDATE_ADMIN_FESTIVALS_FORM_FAILURE';





export const POST_ADMIN_BLOGS_FORM_REQUEST = 'POST_ADMIN_BLOGS_FORM_REQUEST';
export const POST_ADMIN_BLOGS_FORM_SUCCESS = 'POST_ADMIN_BLOGS_FORM_SUCCESS';
export const POST_ADMIN_BLOGS_FORM_FAILURE = 'POST_ADMIN_BLOGS_FORM_FAILURE';

export const GET_ADMIN_BLOGS_FORM_REQUEST = 'GET_ADMIN_BLOGS_FORM_REQUEST';
export const GET_ADMIN_BLOGS_FORM_SUCCESS = 'GET_ADMIN_BLOGS_FORM_SUCCESS';
export const GET_ADMIN_BLOGS_FORM_FAILURE = 'GET_ADMIN_BLOGS_FORM_FAILURE';

export const GET_SINGLE_ADMIN_BLOGS_FORM_REQUEST = 'GET_SINGLE_ADMIN_BLOGS_FORM_REQUEST';
export const GET_SINGLE_ADMIN_BLOGS_FORM_SUCCESS = 'GET_SINGLE_ADMIN_BLOGS_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_BLOGS_FORM_FAILURE = 'GET_SINGLE_ADMIN_BLOGS_FORM_FAILURE';

export const DELETE_ADMIN_BLOGS_FORM_REQUEST = 'DELETE_ADMIN_BLOGS_FORM_REQUEST';
export const DELETE_ADMIN_BLOGS_FORM_SUCCESS = 'DELETE_ADMIN_BLOGS_FORM_SUCCESS';
export const DELETE_ADMIN_BLOGS_FORM_FAILURE = 'DELETE_ADMIN_BLOGS_FORM_FAILURE';

export const UPDATE_ADMIN_BLOGS_FORM_REQUEST = 'UPDATE_ADMIN_BLOGS_FORM_REQUEST';
export const UPDATE_ADMIN_BLOGS_FORM_SUCCESS = 'UPDATE_ADMIN_BLOGS_FORM_SUCCESS';
export const UPDATE_ADMIN_BLOGS_FORM_FAILURE = 'UPDATE_ADMIN_BLOGS_FORM_FAILURE';






export const POST_ADMIN_GALLERY_FORM_REQUEST = 'POST_ADMIN_GALLERY_FORM_REQUEST';
export const POST_ADMIN_GALLERY_FORM_SUCCESS = 'POST_ADMIN_GALLERY_FORM_SUCCESS';
export const POST_ADMIN_GALLERY_FORM_FAILURE = 'POST_ADMIN_GALLERY_FORM_FAILURE';

export const GET_ADMIN_GALLERY_FORM_REQUEST = 'GET_ADMIN_GALLERY_FORM_REQUEST';
export const GET_ADMIN_GALLERY_FORM_SUCCESS = 'GET_ADMIN_GALLERY_FORM_SUCCESS';
export const GET_ADMIN_GALLERY_FORM_FAILURE = 'GET_ADMIN_GALLERY_FORM_FAILURE';

export const GET_SINGLE_ADMIN_GALLERY_FORM_REQUEST = 'GET_SINGLE_ADMIN_GALLERY_FORM_REQUEST';
export const GET_SINGLE_ADMIN_GALLERY_FORM_SUCCESS = 'GET_SINGLE_ADMIN_GALLERY_FORM_SUCCESS';
export const GET_SINGLE_ADMIN_GALLERY_FORM_FAILURE = 'GET_SINGLE_ADMIN_GALLERY_FORM_FAILURE';

export const DELETE_ADMIN_GALLERY_FORM_REQUEST = 'DELETE_ADMIN_GALLERY_FORM_REQUEST';
export const DELETE_ADMIN_GALLERY_FORM_SUCCESS = 'DELETE_ADMIN_GALLERY_FORM_SUCCESS';
export const DELETE_ADMIN_GALLERY_FORM_FAILURE = 'DELETE_ADMIN_GALLERY_FORM_FAILURE';

export const UPDATE_ADMIN_GALLERY_FORM_REQUEST = 'UPDATE_ADMIN_GALLERY_FORM_REQUEST';
export const UPDATE_ADMIN_GALLERY_FORM_SUCCESS = 'UPDATE_ADMIN_GALLERY_FORM_SUCCESS';
export const UPDATE_ADMIN_GALLERY_FORM_FAILURE = 'UPDATE_ADMIN_GALLERY_FORM_FAILURE';